### ISSUE TITLE
The tearDown method has a bug in it

### ISSUE THREAD

**Issue by reden87** [team-supercharge/SCConfiguration#7]
When the `tearDown` method runs the `Configuration2` file gets all the keys and values from the original `Configuration` file. This means the whole content of the `Configuration` file becomes overwritten.

This is problematic because if you want to change something in the `Configuration` file for a new app version the `configValueForKey:` method will give you the old -original- value since the key is overwritten..

**Comment by freeubi** [comment]
Just checked - this bug cause crashes in our applications. 
As i see the problem apply with/out encryption.

Please fix it as soon as you can.

**Comment by freeubi** [comment]
Any development solving this problem?

**Comment by reden87** [comment]
@freeubi sadly not yet. I won't have time in the next 1,5 weeks but after that I probably have time to deal with this. I'll keep you posted.

**Comment by reden87** [comment]
Sorry for the big delay @freeubi the fix is now merged and released to the CocoaPod repo with version number 2.2.0.

You can use it like this:
`pod 'SCConfiguration', '~> 2.2'`


I'm closing this issue now, if you have any other problem you can open a new ticket.
