### ISSUE TITLE
xCode 9 Compatibility

### ISSUE THREAD

**Issue by zcsipler** [team-supercharge/SCConfiguration#8]
Currently you are depending to RNCrypto lib version 2.0 in the podspec file which is not compatible with xCode 9 and makes the build fail. Are you planning to adjust the lib to use the new version of RNCrypto that compatible with xCode 9?

**Comment by reden87** [comment]
@zcsipler We plan to fix the issue. Sadly we cannot update the RNCrypto library because of technical reasons.
We'll have a fix but in the meantime the quick solution is to remove the line which does not compile. See reference here: https://github.com/RNCryptor/RNCryptor-objc/pull/16

**Comment by zcsipler** [comment]
@reden87 thanks for the answer. Yes I know this temporarily solution and this is working in local but it will be difficult with CI.

**Comment by reden87** [comment]
@zcsipler You're right! We'll try to solve this ASAP.

**Comment by reden87** [comment]
@zcsipler fix ETA is next week

**Comment by reden87** [comment]
@zcsipler sorry for the delay, the fix is in development now, most possibly we'll publish it next week.

**Comment by reden87** [comment]
Sorry for the big delay @zcsipler the fix is now merged and released to the CocoaPod repo with version number 2.2.0.

You can use it like this:
`pod 'SCConfiguration', '~> 2.2'`


I'm closing this issue now, if you have any other problem feel free to open a new ticket.
